"""Added user reference to Workflow

Revision ID: 5bd28a46ed08
Revises: 2c0c66843c4c
Create Date: 2025-03-31 13:22:05.602611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd28a46ed08'
down_revision: Union[str, None] = '2c0c66843c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflows', sa.Column('created_by', sa.String(), nullable=False))
    op.create_foreign_key(None, 'workflows', 'users', ['created_by'], ['email'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflows', type_='foreignkey')
    op.drop_column('workflows', 'created_by')
    # ### end Alembic commands ###
